import { DEFENSE_SCHEME_LABELS as DEFENSE_SCHEME_LABELS_REGISTRY, OFFENSE_SCHEME_LABELS as OFFENSE_SCHEME_LABELS_REGISTRY } from "@/lib/displayLabels";

export const OFFENSE_SCHEME_IDS = [
  "AIR_RAID",
  "SHANAHAN_WIDE_ZONE",
  "VERTICAL_PASSING",
  "PRO_STYLE_BALANCED",
  "POWER_GAP",
  "ERHARDT_PERKINS",
  "RUN_AND_SHOOT",
  "SPREAD_RPO",
  "WEST_COAST",
  "AIR_CORYELL",
  "MODERN_TRIPLE_OPTION",
  "CHIP_KELLY_RPO",
  "TWO_TE_POWER_I",
  "MOTION_BASED_MISDIRECTION",
  "POWER_SPREAD",
] as const;

export const DEFENSE_SCHEME_IDS = [
  "THREE_FOUR_TWO_GAP",
  "FOUR_TWO_FIVE",
  "SEATTLE_COVER_3",
  "COVER_SIX",
  "FANGIO_TWO_HIGH",
  "TAMPA_2",
  "MULTIPLE_HYBRID",
  "CHAOS_FRONT",
  "PHILLIPS_BASE_THREE_FOUR",
  "LEBEAU_ZONE_BLITZ_THREE_FOUR",
  "BEARS_FOUR_SIX",
  "FOUR_THREE_OVER",
  "SINGLE_HIGH_COVER_3",
  "SABAN_COVER_4_MATCH",
  "RYAN_NICKEL_PRESSURE",
] as const;

export type OffenseSchemeId = (typeof OFFENSE_SCHEME_IDS)[number];
export type DefenseSchemeId = (typeof DEFENSE_SCHEME_IDS)[number];

export const OFFENSE_SCHEME_LABELS = OFFENSE_SCHEME_LABELS_REGISTRY as Record<OffenseSchemeId, string>;

export const DEFENSE_SCHEME_LABELS = DEFENSE_SCHEME_LABELS_REGISTRY as Record<DefenseSchemeId, string>;

export const DEFAULT_OFFENSE_SCHEME_ID: OffenseSchemeId = "PRO_STYLE_BALANCED";
export const DEFAULT_DEFENSE_SCHEME_ID: DefenseSchemeId = "MULTIPLE_HYBRID";
