const withParam = (pattern: string, token: string, value: string | number) =>
  pattern.replace(token, String(value));

const root = "/" as const;
const hubRoot = "/hub" as const;

export const ROUTES = {
  root,
  loadSave: "/load-save",
  saveMode: "/new-save",
  onboarding: "/onboarding",
  onboardingBackground: "/onboarding/background",
  onboardingOffers: "/onboarding/offers",
  onboardingCoordinators: "/onboarding/coordinators",
  storyInterview: "/story/interview",
  freePlay: "/free-play/setup",
  freePlaySetup: "/free-play/setup",
  hub: hubRoot,
  fired: "/fired",
  pressFeedbackDemo: "/press-feedback-demo",
  skillTree: "/skill-tree",
  settings: "/settings",
  news: "/news",
  coachingOffice: "/coachs-office/*",

  sections: {
    staff: "/staff/*",
    roster: "/roster/*",
    contracts: "/contracts/*",
    strategy: "/strategy/*",
    scouting: "/scouting/*",
    offseason: "/offseason/*",
    freeAgency: "/free-agency/*",
    reSign: "/re-sign/*",
    trades: "/trades/*",
  },

  hubPages: {
    stats: "/hub/stats",
    activity: "/hub/activity",
    ownerRelations: "/hub/owner-relations",
    teamStrategy: "/hub/team-strategy",
    frontOffice: "/hub/front-office",
    firingMeter: "/hub/firing-meter",
    powerRankings: "/hub/power-rankings",
    trades: "/hub/trades",
    reSign: "/hub/re-sign",
    freeAgency: "/hub/free-agency",
    draft: "/hub/draft",
    draftResults: "/hub/draft-results",
    freeAgencyRecap: "/hub/free-agency-recap",
    trainingCamp: "/hub/training-camp",
    cutdowns: "/hub/cutdowns",
    preseason: "/hub/preseason",
    regularSeason: "/hub/regular-season",
    gameplan: "/hub/gameplan",
    playoffs: "/hub/playoffs",
    playoffsBracket: "/hub/playoffs/bracket",
    playoffsGame: "/hub/playoffs/game/:id",
    schedule: "/hub/schedule",
    scheduleWeek: "/hub/schedule/week/:weekNumber",
    scheduleTeam: "/hub/schedule/team/:teamId",
    scheduleGame: "/hub/schedule/game/:gameKey",
    playcall: "/hub/playcall",
    player: "/hub/player/:playerId",
    capProjection: "/hub/cap-projection",
    tagCenter: "/hub/tag-center",
    deadMoney: "/hub/dead-money",
    development: "/hub/development",
    injuryReport: "/hub/injury-report",
    capBaseline: "/hub/cap-baseline",
    rosterAudit: "/hub/roster-audit",
    assistantHiring: "/hub/assistant-hiring",
    coordinatorHiring: "/hub/coordinator-hiring",
    hallOfFame: "/hub/hall-of-fame",
    leagueHistory: "/hub/league-history",
    analytics: "/hub/analytics",
    combine: "/hub/combine",
    tampering: "/hub/tampering",
    preDraft: "/hub/pre-draft",
    resignAlias: "/hub/resign",
    scoutingLegacy: "/hub/scouting/*",
    offseasonLegacy: "/hub/offseason/*",
  },

  scouting: {
    root: "/scouting",
    wildcard: "/scouting/*",
    bigBoard: "/scouting/big-board",
    combine: "/scouting/combine",
    prospect: "/scouting/prospect/:prospectId",
    privateWorkouts: "/scouting/private-workouts",
    workoutsLegacy: "/scouting/workouts",
    interviews: "/scouting/interviews",
    medical: "/scouting/medical",
    allocation: "/scouting/allocation",
    inSeason: "/scouting/in-season",
  },

  offseason: {
    root: "/offseason",
    wildcard: "/offseason/*",
    draft: "/offseason/draft",
    trainingCamp: "/offseason/training-camp",
    cutdowns: "/offseason/cutdowns",
    combine: "/offseason/combine",
    preDraft: "/offseason/pre-draft",
  },

  roster: {
    root: "/roster",
    players: "/roster/players",
    player: "/roster/player/:playerId",
    depthChart: "/roster/depth-chart",
    development: "/roster/development",
    injuryReport: "/roster/injury-report",
    audit: "/roster/audit",
  },

  contracts: {
    capProjection: "/contracts/cap-projection",
    tag: "/contracts/tag",
    deadMoney: "/contracts/dead-money",
    capBaseline: "/contracts/cap-baseline",
    rosterAudit: "/contracts/roster-audit",
  },

  legacy: {
    background: "/background",
    offers: "/offers",
    coordinators: "/coordinators",
  },

  helpers: {
    hubPlayoffGame: (id: string | number) => withParam("/hub/playoffs/game/:id", ":id", id),
    hubScheduleWeek: (weekNumber: string | number) => withParam("/hub/schedule/week/:weekNumber", ":weekNumber", weekNumber),
    hubScheduleTeam: (teamId: string | number) => withParam("/hub/schedule/team/:teamId", ":teamId", teamId),
    hubScheduleGame: (gameKey: string | number) => withParam("/hub/schedule/game/:gameKey", ":gameKey", gameKey),
    hubPlayer: (playerId: string | number) => withParam("/hub/player/:playerId", ":playerId", playerId),
    rosterPlayer: (playerId: string | number) => withParam("/roster/player/:playerId", ":playerId", playerId),
    scoutingProspect: (prospectId: string | number) => withParam("/scouting/prospect/:prospectId", ":prospectId", prospectId),
    scoutingWildcard: (wildcard?: string) => (wildcard ? `/scouting/${wildcard}` : "/scouting"),
    offseasonWildcard: (wildcard?: string) => (wildcard ? `/offseason/${wildcard}` : "/offseason"),
  },

  phase: {
    create: "/onboarding",
    background: "/onboarding/background",
    interviews: "/story/interview",
    offers: "/onboarding/offers",
    coordinatorHiring: "/onboarding/coordinators",
    hub: "/hub",
  },

  redirects: {
    hubToPrimary: {
      scouting: "/scouting",
      offseason: "/offseason",
      freeAgency: "/free-agency",
      draft: "/offseason/draft",
      trainingCamp: "/offseason/training-camp",
      cutdowns: "/offseason/cutdowns",
      combine: "/offseason/combine",
      tampering: "/free-agency",
      preDraft: "/offseason/pre-draft",
      resignAlias: "/hub/re-sign",
    },
    hubToContracts: {
      capProjection: "/contracts/cap-projection",
      tagCenter: "/contracts/tag",
      deadMoney: "/contracts/dead-money",
      capBaseline: "/contracts/cap-baseline",
    },
    hubToRoster: {
      development: "/roster/development",
      injuryReport: "/roster/injury-report",
      rosterAudit: "/roster/audit",
      playerFallback: "/roster/players",
    },
    hubToStaff: {
      assistantHiring: "/staff/hire",
    },
    contractsToRoster: {
      rosterAudit: "/roster/audit",
    },
    rosterDefault: "/roster/depth-chart",
    scoutingWorkoutsLegacy: "/scouting/private-workouts",
  },
} as const;

export type AppRoutes = typeof ROUTES;
