import { useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { useGame } from "@/context/GameContext";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getPositionLabel } from "@/lib/displayLabels";
const ROSTER = Array.from({ length: 60 }, (_, i) => ({ id: `R_${(i + 1).toString().padStart(3, "0")}`, name: `Player ${(i + 1).toString().padStart(2, "0")}`, pos: ["QB", "RB", "WR", "TE", "OL", "DL", "LB", "DB"][i % 8], ovr: 55 + ((i * 7) % 35) }));

export default function CutDowns() { const { state, dispatch } = useGame(); const navigate = useNavigate(); const decisions = state.offseasonData.cutDowns.decisions; const keptCount = useMemo(() => { const cut = new Set(Object.entries(decisions).filter(([, d]) => d.keep === false).map(([id]) => id)); return ROSTER.filter((p) => !cut.has(p.id)).length; }, [decisions]); const toggle = (id: string) => dispatch({ type: "CUT_TOGGLE", payload: { playerId: id } }); const completeStep = () => dispatch({ type: "OFFSEASON_COMPLETE_STEP", payload: { stepId: "CUT_DOWNS" } }); const enterWeek1 = () => { if (!state.offseason.stepsComplete.CUT_DOWNS) return; navigate("/hub/regular-season"); }; return <div className="p-4 md:p-8 space-y-4"><Card><CardContent className="p-6 flex items-center justify-between"><div className="space-y-1"><div className="text-xl font-bold">Final Cut Downs</div><div className="text-sm text-muted-foreground">Cut to 53 (MVP: toggle cut).</div></div><Badge variant="outline">Step 9</Badge></CardContent></Card><Card><CardContent className="p-6 flex flex-wrap items-center justify-between gap-3"><div className="text-sm text-muted-foreground">Roster size: <span className="font-medium">{keptCount}</span> / 53</div><div className="flex gap-2"><Button variant="outline" onClick={completeStep} disabled={keptCount !== 53}>Complete Step</Button><Button onClick={enterWeek1} disabled={!state.offseason.stepsComplete.CUT_DOWNS || keptCount !== 53}>Enter Week 1 →</Button></div></CardContent></Card><Card><CardContent className="p-5 space-y-3"><div className="flex items-center justify-between"><div className="font-semibold">Roster</div><Badge variant="outline">{ROSTER.length}</Badge></div><div className="space-y-2 max-h-[560px] overflow-auto pr-1">{ROSTER.map((p) => { const keep = decisions[p.id]?.keep !== false; return <div key={p.id} className="border rounded-md px-3 py-2 flex items-center justify-between"><div className="min-w-0"><div className="font-medium truncate">{p.name} <span className="text-muted-foreground">({getPositionLabel(p.pos)})</span></div><div className="text-xs text-muted-foreground">OVR {p.ovr}</div></div><Button size="sm" variant={keep ? "outline" : "default"} onClick={() => toggle(p.id)}>{keep ? "Cut" : "Keep"}</Button></div>; })}</div></CardContent></Card></div>; }