import type { OffenseSchemeId } from "@/lib/schemeLabels";

export type QBArchetypeTag = "POCKET_PURE" | "DUAL_THREAT" | "SCRAMBLER" | "GAME_MANAGER" | "IMPROVISER";

const SCHEME_DEFAULTS: Record<OffenseSchemeId, number> = {
  AIR_RAID: 1,
  SHANAHAN_WIDE_ZONE: 1,
  VERTICAL_PASSING: 1,
  PRO_STYLE_BALANCED: 1,
  POWER_GAP: 1,
  ERHARDT_PERKINS: 1,
  RUN_AND_SHOOT: 1,
  SPREAD_RPO: 1,
  WEST_COAST: 1,
  AIR_CORYELL: 1,
  MODERN_TRIPLE_OPTION: 1,
  CHIP_KELLY_RPO: 1,
  TWO_TE_POWER_I: 1,
  MOTION_BASED_MISDIRECTION: 1,
  POWER_SPREAD: 1,
};

const dtFavored = {
  SPREAD_RPO: 1.15,
  CHIP_KELLY_RPO: 1.12,
  MODERN_TRIPLE_OPTION: 1.1,
  POWER_SPREAD: 1.08,
  PRO_STYLE_BALANCED: 0.88,
} as const;

export const QB_TUNING = {
  PRESSURE_THRESHOLD: 0.54,
  SCRAMBLE_DISCIPLINE_BREAKPOINT: 44,
  DISCIPLINE_HIGH_THRESHOLD: 72,
  BASE_QB_RUN_INJURY_RATE: 0.015,
  SLIDE_RISK_SCALAR: 0.85,
  CONTACT_THRESHOLD_PER_SEASON: 24,
  DURABILITY_DECAY_LOW_SLIDE: 1,
  DIVERGENCE_POCKET: 10,
  DIVERGENCE_DUAL_THREAT: 16,
  DIVERGENCE_IMPROVISER: 14,
  REVEAL_THRESHOLD_SCRAMBLE_DISCIPLINE: 64,
  REVEAL_THRESHOLD_RPO_RATING: 58,
  AUTO_TAG_THRESHOLDS: {
    DUAL_THREAT_MOBILITY_MIN: 82,
    DUAL_THREAT_PASSING_MIN: 70,
    SCRAMBLER_MOBILITY_MIN: 86,
    GAME_MANAGER_DECISION_MIN: 82,
    POCKET_MOBILITY_MAX: 66,
  },
  SCHEME_FIT_MULTIPLIERS: {
    POCKET_PURE: { ...SCHEME_DEFAULTS, PRO_STYLE_BALANCED: 1.1, ERHARDT_PERKINS: 1.08, TWO_TE_POWER_I: 1.05, SPREAD_RPO: 0.9 },
    DUAL_THREAT: { ...SCHEME_DEFAULTS, ...dtFavored },
    SCRAMBLER: { ...SCHEME_DEFAULTS, SPREAD_RPO: 1.1, CHIP_KELLY_RPO: 1.1, MODERN_TRIPLE_OPTION: 1.14, PRO_STYLE_BALANCED: 0.9 },
    GAME_MANAGER: { ...SCHEME_DEFAULTS, WEST_COAST: 1.08, PRO_STYLE_BALANCED: 1.05, AIR_RAID: 0.95, MODERN_TRIPLE_OPTION: 0.9 },
    IMPROVISER: { ...SCHEME_DEFAULTS, RUN_AND_SHOOT: 1.08, AIR_RAID: 1.06, SPREAD_RPO: 1.04, TWO_TE_POWER_I: 0.9 },
  } as Record<QBArchetypeTag, Record<OffenseSchemeId, number>>,
} as const;

export const QB_TUNING_DERIVED = {
  SCRAMBLE_DISCIPLINE_MIDPOINT: Math.round((QB_TUNING.SCRAMBLE_DISCIPLINE_BREAKPOINT + QB_TUNING.DISCIPLINE_HIGH_THRESHOLD) / 2),
  RUN_INJURY_RATE_CAP: QB_TUNING.BASE_QB_RUN_INJURY_RATE * (1 + QB_TUNING.SLIDE_RISK_SCALAR),
};
